### ISSUE TITLE
Link to blog post is broken

### ISSUE THREAD

**Issue by Akeboshiwind** [brandonbloom/backtick#11]
Hi, looks like the blog went down at some point.
I'm not sure if this is temporary, but the wayback machine has a copy: https://web.archive.org/web/20160322115942/http://www.brandonbloom.name/blog/2012/11/23/templating-clojures-backtick/

**Comment by brandonbloom** [comment]
Correct link is now https://www.brandonbloom.name/blog/2012/11/23/templating-clojures-backtick/

I've updated the readme. Thanks!
