### ISSUE TITLE
CLJ-1403 changes to ns-resolve

### ISSUE THREAD

**Issue by brandonbloom** [brandonbloom/backtick#5]
Fixing http://dev.clojure.org/jira/browse/CLJ-1403 will probably break `ns-resolve-sym`.

/cc @bronsa https://twitter.com/Bronsa_/status/605091084449005569

**Comment by NoahTheDuke** [comment]
This was finally released in 1.10.

**Comment by brandonbloom** [comment]
Pull requests welcome on this issue. Thanks.

**Comment by NoahTheDuke** [comment]
Sorry for the delay, lol.
