### ISSUE TITLE
Avoiding resolving symbols within a local scope?

### ISSUE THREAD

**Issue by daveyarwood** [brandonbloom/backtick#6]
Hi -- backtick is really awesome! We're using it to provide inline Clojure code for [Alda](http://github.com/alda-lang/alda). It mostly works great, but there is still one wrinkle that we haven't quite been able to solve -- [symbols within a let binding are resolved just like any other symbol](https://github.com/alda-lang/alda/pull/109#issuecomment-143757755). This may or may not be a solvable problem, but at any rate, I wanted to see if you have any ideas.

Our use case: We want to read Clojure code from strings and evaluate it within the context of the `alda.lisp` namespace, which has a bunch of useful things defined for the user's convenience.

```clojure
(defquote alda-lisp-quote
  #(if-let [{:keys [ns name]} (meta (ns-resolve 'alda.lisp %))]
     (symbol (str ns "/" name))
     %))

(defn read-to-alda-lisp
  [code]
  (load-string (format "(alda.parser/alda-lisp-quote %s)" code)))
```

The idea is that each symbol attempts to be resolved in `alda.lisp` (if this succeeds, we get something like `alda.lisp/tempo` or `clojure.core/println`), and if this fails, then the symbol stays as-is (e.g. `x`), so that when the code is eval'd, the Clojure reader will attempt to read it as a locally scoped symbol or within the current namespace, depending on the context.

This appears to work in every case except for the one where you create a local binding that happens to have the same name as something defined in `alda.lisp` -- it will resolve to `alda.lisp/that-thing` instead of `that-thing`.

Do you know if there is a way, using backtick, to only attempt to resolve a symbol if it is not supposed to be in some scope? The Clojure reader apparently does this somehow, but I'm not familiar enough with Clojure's internals to know how exactly.

**Comment by brandonbloom** [comment]
Backtick is an implementation of syntax-quote, which operates at the reader level. While Clojure's syntax-quote does leverage knowledge of the dynamic environment (namespaces, vars, etc), it does not have any notion of lexical scope or any high-level understanding of Clojure forms. When your templating code, the normal advice for writing macros applies: Use gensyms:

```
`(let [tempo# 1] (+ 1 tempo#))
```

But really, you probably don't want syntax-quote or backtick at all for this use case. Instead, use the normal reader, wrap with `#(list 'fn [] %) and use a combination of in-ns/use/eval.

**Comment by daveyarwood** [comment]
That makes sense. I hadn't thought of wrapping the code in an anonymous function and using in-ns/eval -- will give that a try. Thanks!
